services:
  bank-loans-mysqldb:
    container_name: mysql-container
    image: mysql:8.0.40
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - "/home/username/database:/var/lib/mysql"
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: bank-loans-mysqldb
    networks:
      - internalnet

  bank-loans-nodeapp:
    container_name: nodeapp-container
    build: .
    image: nodeapp:v1
    ports:
      - 3000:3000
    expose: 
      - 3000
    depends_on:
      - bank-loans-mysqldb
    environment:
      PORT: ${PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      SERVICE_TAGS: prod
      SERVICE_NAME: bank-loans-nodeapp
    volumes:
      - .:/app
      - /app/node_modules
    x-deploy:
      file_watcher:
        watch: true
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge