services:
  bank-loans-mysqldb:
    container_name: mysql-container
    image: mysql:8.0.40
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - "/home/username/database:/var/lib/mysql"
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: bank_loans
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: prod
      SERVICE_NAME: bank-loans-mysqldb
    networks:
      - internalnet

  bank-loans-nodeapp:
    container_name: nodeapp-container
    build: .  
    image: nodeapp:v1
    ports:
      - 3000:3000
    expose: 
      - 3000
    depends_on:
      - bank-loans-mysqldb
    environment:
      PORT: 3000  
      DATABASE_HOST: bank-loans-mysqldb
      DATABASE_NAME: bank_loans
      DATABASE_PASSWORD: 'admin'
      DATABASE_USERNAME: admin
      EMAIL_USERNAME: 0fa914e31e6ca1
      EMAIL_PASSWORD: 8fef63bdb60d85
      EMAIL_HOST: sandbox.smtp.mailtrap.io
      EMAIL_PORT: 2525
      SERVICE_TAGS: prod
      SERVICE_NAME: bank-loans-nodeapp
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge